# Compliance Data  -- Monthly Report

In [1]:
import pandas as pd
import numpy as np

In [2]:
###Import data
##1. Find file in finder
##2. Option + Command + C
##3. Paste Info read_csv(r” ”)

#Data file merges with All Dates when all data is saved from Access. When saved from SQL, the data does not merge accurately.

df = pd.ExcelFile(r"/Users/holly/Desktop/nycdoe/01142021 Compliance Data v3 ACCESS.xlsx")

In [3]:
#Read data from corrrect tab.

ideation = df.parse('Ideation')
acs = df.parse('ACS')
missing = df.parse('MISSING')
inc = df.parse('L1-5')
material = df.parse('Material')
alldates = df.parse('All Dates')

In [4]:
alldates.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        365 non-null    datetime64[ns]
 1   Day of Week                 365 non-null    object
 2   School Day                  365 non-null    object
 3   Nearest School Day          365 non-null    datetime64[ns]
 4   Final Day to ENTER - 1 Day  365 non-null    datetime64[ns]
 5   2 Days                      365 non-null    datetime64[ns]
 6   5 Days                      365 non-null    datetime64[ns]
 7   10 Days                     365 non-null    datetime64[ns]
dtypes: datetime64[ns](6), object(2)
memory usage: 22.9+ KB

**SUICIDE IDEATION**

1. Import Incident Data
2. Merge with All Dates -- Join on Data
3. Add Final Day to ENTER - 1 Day, 10 Days from All Dates table
4. Create field: Entered on Time: If OccDateEntered <= Final Day to Enter - 1 Day --> YES, otherwise, NO
5. Create field: Updated on Time: If Updated Date <= 10 Days --> YES, otherwise, NO
6. If Updated Data is Blank, leave Updated on Time Blank.

In [6]:
#schools_susptype = schools.merge(susptypefinal, left_on='DBN', right_on='ATS', how='left')
ideation_df = ideation.merge(alldates, left_on='Date', right_on='Date', how='left')

In [7]:
#schools_susptype.drop('ATS', axis = 1, inplace = True)
#Drop Day of Week, School Day, Nearest School Day, 2 Days, 5 Days
ideation_df.drop('Day of Week', axis = 1, inplace = True)
ideation_df.drop('School Day', axis = 1, inplace = True)
ideation_df.drop('Nearest School Day', axis = 1, inplace = True)
ideation_df.drop('2 Days', axis = 1, inplace = True)
ideation_df.drop('5 Days', axis = 1, inplace = True)
ideation_df.drop('UpdatedText', axis = 1, inplace = True)
ideation_df.drop('EventType', axis = 1, inplace = True)

In [8]:
ideation_df

,RowNumber,AcademicYear,ATS,School Name,ControlNo,Code,EIC,Date,PrincInformed,OccDateEntered,Updated Date,WhoSource,Final Day to ENTER - 1 Day,10 Days
0,1,2020-2021,15K010,"Magnet School of Math, Science and Design Tech...",15K010-091720-0004,O57,False,2020-09-17,2020-09-17,2020-09-17,2020-09-18,CENTRAL\GOramas,2020-09-18,2020-10-02
1,1,2020-2021,10X565,High School for Energy and Technology,10X565-092120-0005,O57,False,2020-09-21,2020-09-22,2020-09-22,2020-09-22,CENTRAL\VWilliams10,2020-09-22,2020-10-06
2,1,2020-2021,10X445,Bronx High School of Science,10X445-092220-0010,O57,False,2020-09-22,2020-09-22,2020-09-22,2020-09-23,CENTRAL\DHeckman,2020-09-23,2020-10-07
3,1,2020-2021,10X445,Bronx High School of Science,10X445-092920-0012,O57,False,2020-09-29,2020-09-29,2020-09-29,2020-10-02,CENTRAL\DHeckman,2020-09-30,2020-10-14
4,1,2020-2021,10X046,P.S. 046 Edgar Allan Poe,10X046-092920-0006,O57,False,2020-09-29,2020-09-29,2020-09-30,2020-10-07,CENTRAL\EMaydwell,2020-09-30,2020-10-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1412,1,2020-2021,27Q146,P.S. 146 Howard Beach,27Q146-121220-0016,O57,False,2020-12-12,2021-01-13,2021-01-13,2021-01-19,CENTRAL\CBrowne6,2020-12-14,2021-01-05
1413,1,2020-2021,24Q229,P.S. 229 Emanuel Kaplan,24Q229-011521-0018,O57,False,2021-01-15,2021-01-15,2021-01-15,2021-01-22,CENTRAL\EGarrit,2021-01-19,2021-02-01
1414,1,2020-2021,21K215,P.S. 215 Morris H. Weiss,21K215-011521-0028,O57,False,2021-01-15,2021-01-15,2021-01-15,2021-01-19,CENTRAL\NBocchi,2021-01-19,2021-02-01
1415,1,2020-2021,09X128,Mott Hall III,09X128-011921-0027,O57,True,2021-01-19,2021-01-19,2021-01-20,2021-01-20,CENTRAL\SSimmon2,2021-01-20,2021-02-02
1416,1,2020-2021,75X017,P.S. X017,75X017-012021-0101,O57,True,2021-01-20,2021-01-20,2021-01-20,2021-01-20,CENTRAL\SSimmon2,2021-01-21,2021-02-03

In [9]:
#Create fileds: Entered on Time: If OccDateEntered <= Final Day to Enter - 1 Day --> YES, otherwise, NO
#Source: https://www.geeksforgeeks.org/python-creating-a-pandas-dataframe-column-based-on-a-given-condition/
#df['hasimage'] = np.where(df['photos']!= '[]', True, False)  
#Source: https://www.dataquest.io/blog/tutorial-add-column-pandas-dataframe-based-on-if-else-condition/
#df['Price'] = [1500 if x =='Music' else 800 for x in df['Event']] 

ideation_df['Entered on Time'] = np.where(ideation_df['OccDateEntered'] <= ideation_df['Final Day to ENTER - 1 Day'], 'YES', 'NO')

In [10]:
ideation_df

,RowNumber,AcademicYear,ATS,School Name,ControlNo,Code,EIC,Date,PrincInformed,OccDateEntered,Updated Date,WhoSource,Final Day to ENTER - 1 Day,10 Days,Entered on Time
0,1,2020-2021,15K010,"Magnet School of Math, Science and Design Tech...",15K010-091720-0004,O57,False,2020-09-17,2020-09-17,2020-09-17,2020-09-18,CENTRAL\GOramas,2020-09-18,2020-10-02,YES
1,1,2020-2021,10X565,High School for Energy and Technology,10X565-092120-0005,O57,False,2020-09-21,2020-09-22,2020-09-22,2020-09-22,CENTRAL\VWilliams10,2020-09-22,2020-10-06,YES
2,1,2020-2021,10X445,Bronx High School of Science,10X445-092220-0010,O57,False,2020-09-22,2020-09-22,2020-09-22,2020-09-23,CENTRAL\DHeckman,2020-09-23,2020-10-07,YES
3,1,2020-2021,10X445,Bronx High School of Science,10X445-092920-0012,O57,False,2020-09-29,2020-09-29,2020-09-29,2020-10-02,CENTRAL\DHeckman,2020-09-30,2020-10-14,YES
4,1,2020-2021,10X046,P.S. 046 Edgar Allan Poe,10X046-092920-0006,O57,False,2020-09-29,2020-09-29,2020-09-30,2020-10-07,CENTRAL\EMaydwell,2020-09-30,2020-10-14,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1412,1,2020-2021,27Q146,P.S. 146 Howard Beach,27Q146-121220-0016,O57,False,2020-12-12,2021-01-13,2021-01-13,2021-01-19,CENTRAL\CBrowne6,2020-12-14,2021-01-05,NO
1413,1,2020-2021,24Q229,P.S. 229 Emanuel Kaplan,24Q229-011521-0018,O57,False,2021-01-15,2021-01-15,2021-01-15,2021-01-22,CENTRAL\EGarrit,2021-01-19,2021-02-01,YES
1414,1,2020-2021,21K215,P.S. 215 Morris H. Weiss,21K215-011521-0028,O57,False,2021-01-15,2021-01-15,2021-01-15,2021-01-19,CENTRAL\NBocchi,2021-01-19,2021-02-01,YES
1415,1,2020-2021,09X128,Mott Hall III,09X128-011921-0027,O57,True,2021-01-19,2021-01-19,2021-01-20,2021-01-20,CENTRAL\SSimmon2,2021-01-20,2021-02-02,YES
1416,1,2020-2021,75X017,P.S. X017,75X017-012021-0101,O57,True,2021-01-20,2021-01-20,2021-01-20,2021-01-20,CENTRAL\SSimmon2,2021-01-21,2021-02-03,YES

In [11]:
ideation_df['Updated on Time'] = np.where(ideation_df['Updated Date'] <= ideation_df['10 Days'], 'YES', 'NO')

In [12]:
ideation_df

,RowNumber,AcademicYear,ATS,School Name,ControlNo,Code,EIC,Date,PrincInformed,OccDateEntered,Updated Date,WhoSource,Final Day to ENTER - 1 Day,10 Days,Entered on Time,Updated on Time
0,1,2020-2021,15K010,"Magnet School of Math, Science and Design Tech...",15K010-091720-0004,O57,False,2020-09-17,2020-09-17,2020-09-17,2020-09-18,CENTRAL\GOramas,2020-09-18,2020-10-02,YES,YES
1,1,2020-2021,10X565,High School for Energy and Technology,10X565-092120-0005,O57,False,2020-09-21,2020-09-22,2020-09-22,2020-09-22,CENTRAL\VWilliams10,2020-09-22,2020-10-06,YES,YES
2,1,2020-2021,10X445,Bronx High School of Science,10X445-092220-0010,O57,False,2020-09-22,2020-09-22,2020-09-22,2020-09-23,CENTRAL\DHeckman,2020-09-23,2020-10-07,YES,YES
3,1,2020-2021,10X445,Bronx High School of Science,10X445-092920-0012,O57,False,2020-09-29,2020-09-29,2020-09-29,2020-10-02,CENTRAL\DHeckman,2020-09-30,2020-10-14,YES,YES
4,1,2020-2021,10X046,P.S. 046 Edgar Allan Poe,10X046-092920-0006,O57,False,2020-09-29,2020-09-29,2020-09-30,2020-10-07,CENTRAL\EMaydwell,2020-09-30,2020-10-14,YES,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1412,1,2020-2021,27Q146,P.S. 146 Howard Beach,27Q146-121220-0016,O57,False,2020-12-12,2021-01-13,2021-01-13,2021-01-19,CENTRAL\CBrowne6,2020-12-14,2021-01-05,NO,NO
1413,1,2020-2021,24Q229,P.S. 229 Emanuel Kaplan,24Q229-011521-0018,O57,False,2021-01-15,2021-01-15,2021-01-15,2021-01-22,CENTRAL\EGarrit,2021-01-19,2021-02-01,YES,YES
1414,1,2020-2021,21K215,P.S. 215 Morris H. Weiss,21K215-011521-0028,O57,False,2021-01-15,2021-01-15,2021-01-15,2021-01-19,CENTRAL\NBocchi,2021-01-19,2021-02-01,YES,YES
1415,1,2020-2021,09X128,Mott Hall III,09X128-011921-0027,O57,True,2021-01-19,2021-01-19,2021-01-20,2021-01-20,CENTRAL\SSimmon2,2021-01-20,2021-02-02,YES,YES
1416,1,2020-2021,75X017,P.S. X017,75X017-012021-0101,O57,True,2021-01-20,2021-01-20,2021-01-20,2021-01-20,CENTRAL\SSimmon2,2021-01-21,2021-02-03,YES,YES

In [13]:
#Updated on Time: If Updated Date <= 10 Days --> YES, otherwise, NO
#ideation_df['Entered on Time'] = np.where(ideation_df['OccDateEntered'] <= ideation_df['Final Day to ENTER - 1 Day'], 'YES', 'NO')
ideation_df['Updated on Time'] = np.where(ideation_df['Updated Date'].isnull(), ' ', ideation_df['Updated on Time'])

In [14]:
ideation_df

,RowNumber,AcademicYear,ATS,School Name,ControlNo,Code,EIC,Date,PrincInformed,OccDateEntered,Updated Date,WhoSource,Final Day to ENTER - 1 Day,10 Days,Entered on Time,Updated on Time
0,1,2020-2021,15K010,"Magnet School of Math, Science and Design Tech...",15K010-091720-0004,O57,False,2020-09-17,2020-09-17,2020-09-17,2020-09-18,CENTRAL\GOramas,2020-09-18,2020-10-02,YES,YES
1,1,2020-2021,10X565,High School for Energy and Technology,10X565-092120-0005,O57,False,2020-09-21,2020-09-22,2020-09-22,2020-09-22,CENTRAL\VWilliams10,2020-09-22,2020-10-06,YES,YES
2,1,2020-2021,10X445,Bronx High School of Science,10X445-092220-0010,O57,False,2020-09-22,2020-09-22,2020-09-22,2020-09-23,CENTRAL\DHeckman,2020-09-23,2020-10-07,YES,YES
3,1,2020-2021,10X445,Bronx High School of Science,10X445-092920-0012,O57,False,2020-09-29,2020-09-29,2020-09-29,2020-10-02,CENTRAL\DHeckman,2020-09-30,2020-10-14,YES,YES
4,1,2020-2021,10X046,P.S. 046 Edgar Allan Poe,10X046-092920-0006,O57,False,2020-09-29,2020-09-29,2020-09-30,2020-10-07,CENTRAL\EMaydwell,2020-09-30,2020-10-14,YES,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1412,1,2020-2021,27Q146,P.S. 146 Howard Beach,27Q146-121220-0016,O57,False,2020-12-12,2021-01-13,2021-01-13,2021-01-19,CENTRAL\CBrowne6,2020-12-14,2021-01-05,NO,NO
1413,1,2020-2021,24Q229,P.S. 229 Emanuel Kaplan,24Q229-011521-0018,O57,False,2021-01-15,2021-01-15,2021-01-15,2021-01-22,CENTRAL\EGarrit,2021-01-19,2021-02-01,YES,YES
1414,1,2020-2021,21K215,P.S. 215 Morris H. Weiss,21K215-011521-0028,O57,False,2021-01-15,2021-01-15,2021-01-15,2021-01-19,CENTRAL\NBocchi,2021-01-19,2021-02-01,YES,YES
1415,1,2020-2021,09X128,Mott Hall III,09X128-011921-0027,O57,True,2021-01-19,2021-01-19,2021-01-20,2021-01-20,CENTRAL\SSimmon2,2021-01-20,2021-02-02,YES,YES
1416,1,2020-2021,75X017,P.S. X017,75X017-012021-0101,O57,True,2021-01-20,2021-01-20,2021-01-20,2021-01-20,CENTRAL\SSimmon2,2021-01-21,2021-02-03,YES,YES

In [34]:
#Export data to excel: https://datatofish.com/export-dataframe-to-excel/
#df.to_excel(r'Path to store the exported excel file\File Name.xlsx', sheet_name='Your sheet name', index = False)
#Formatting: https://xlsxwriter.readthedocs.io/working_with_pandas.html

#ideation_df.to_excel(r"/Users/holly/Desktop/nycdoe/01142021 Compliance Data FINAL.xlsx", sheet_name='Ideation',header=True, merge_cells=False, index=False)

**ACS**

1. Import ACS Data
2. Merge with All Dates -- Join on Date
3. Add Final Day to ENTER - 1 Day, 10 Days from All Dates table
4. Create field: Entered on Time: If OccDateEntered <= Final Day to Enter - 1 Day --> YES, otherwise, NO

In [16]:
acs_df = acs.merge(alldates, left_on='Date', right_on='Date', how='left')

In [17]:
acs_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2803 entries, 0 to 2802
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   DBN                         2803 non-null   object
 1   School Name                 2803 non-null   object
 2   Code                        2803 non-null   object
 3   EIC                         2803 non-null   bool
 4   OORS#                       2803 non-null   object
 5   Date                        2803 non-null   datetime64[ns]
 6   PrincInformed               2803 non-null   datetime64[ns]
 7   OccDateEntered              2803 non-null   datetime64[ns]
 8   Academic Year               2803 non-null   object
 9   PreparedBy                  2803 non-null   object
 10  PreparedByEmail             2292 non-null   object
 11  WhoSource                   2803 non-null   object
 12  EventType                   2803 non-null   object
 13  Unnamed: 13                 7 non-null      object
 14  Day of Week                 2803 non-null   object
 15  School Day                  2803 non-null   object
 16  Nearest School Day          2803 non-null   datetime64[ns]
 17  Final Day to ENTER - 1 Day  2803 non-null   datetime64[ns]
 18  2 Days                      2803 non-null   datetime64[ns]
 19  5 Days                      2803 non-null   datetime64[ns]
 20  10 Days                     2803 non-null   datetime64[ns]
dtypes: bool(1), datetime64[ns](8), object(12)
memory usage: 462.6+ KB

In [18]:
acs_df.tail()

,DBN,School Name,Code,EIC,OORS#,Date,PrincInformed,OccDateEntered,Academic Year,PreparedBy,...,WhoSource,EventType,Unnamed: 13,Day of Week,School Day,Nearest School Day,Final Day to ENTER - 1 Day,2 Days,5 Days,10 Days
2798,08X152,P.S. 152 Evergreen,O77,False,08X152-012121-0027,2021-01-21,2021-01-21,2021-01-21,2020-2021,Angela Vera,...,CENTRAL\AVera2,Entered,NaN,Thursday,Yes,2021-01-21,2021-01-22,2021-01-25,2021-01-28,2021-02-04
2799,12X150,P.S. 150 Charles James Fox,O77,False,12X150-012121-0018,2021-01-21,2021-01-21,2021-01-21,2020-2021,Ms. Kelly Padilla LCSW,...,CENTRAL\kpadill,Entered,NaN,Thursday,Yes,2021-01-21,2021-01-22,2021-01-25,2021-01-28,2021-02-04
2800,11X076,P.S. 076 The Bennington School,O77,False,11X076-012121-0048,2021-01-21,2021-01-21,2021-01-21,2020-2021,Micaela Tomasetti,...,CENTRAL\MTomasetti,Entered,NaN,Thursday,Yes,2021-01-21,2021-01-22,2021-01-25,2021-01-28,2021-02-04
2801,27Q183,P.S. 183 Dr. Richard R. Green,O77,False,27Q183-012121-0021,2021-01-21,2021-01-21,2021-01-21,2020-2021,Rhea Peykarian,...,CENTRAL\RPeykarian,Entered,NaN,Thursday,Yes,2021-01-21,2021-01-22,2021-01-25,2021-01-28,2021-02-04
2802,75K811,P.S. K811 Connie Lekas School,O77,False,75K811-012121-0011,2021-01-21,2021-01-21,2021-01-21,2020-2021,A Waterman French,...,CENTRAL\AWatermanFrench,Entered,NaN,Thursday,Yes,2021-01-21,2021-01-22,2021-01-25,2021-01-28,2021-02-04

In [19]:
#Drop Day of Week, School Day, Nearest School Day, 2 Days, 5 Days
acs_df.drop('Code', axis = 1, inplace = True)
acs_df.drop('EIC', axis = 1, inplace = True)
acs_df.drop('Academic Year', axis = 1, inplace = True)
acs_df.drop('EventType', axis = 1, inplace = True)
acs_df.drop('Day of Week', axis = 1, inplace = True)
acs_df.drop('School Day', axis = 1, inplace = True)
acs_df.drop('Nearest School Day', axis = 1, inplace = True)
acs_df.drop('2 Days', axis = 1, inplace = True)
acs_df.drop('5 Days', axis = 1, inplace = True)
acs_df.drop('10 Days', axis = 1, inplace = True)
acs_df.drop('Unnamed: 13', axis = 1, inplace = True)

In [20]:
acs_df.head()

,DBN,School Name,OORS#,Date,PrincInformed,OccDateEntered,PreparedBy,PreparedByEmail,WhoSource,Final Day to ENTER - 1 Day
0,75Q009,P.S. 009,75Q009-070120-0001,2020-07-01,2020-07-01,2020-07-01,John Gonzalez AP,jgonzal5@schools.nyc.gov,CENTRAL\JGonzal5,2020-07-02
1,02M298,Pace High School,02M298-070220-0001,2020-07-02,2020-07-02,2020-07-02,ERIC GLATZ,eglatz@schools.nyc.gov,CENTRAL\EGlatz,2020-07-06
2,06M468,High School for Health Careers and Sciences,06M468-070220-0001,2020-07-02,2020-07-02,2020-07-02,Javier Trejo,JTrejo@schools.nyc.gov,CENTRAL\JTrejo,2020-07-06
3,31R455,Tottenville High School,31R455-070420-0001,2020-07-04,2020-07-06,2020-07-06,D Pugliese,NaN,CENTRAL\GPaglia,2020-07-06
4,31R455,Tottenville High School,31R455-070420-0002,2020-07-04,2020-07-06,2020-07-06,D Jackson,NaN,CENTRAL\GPaglia,2020-07-06

In [21]:
acs_df['Entered on Time'] = np.where(acs_df['OccDateEntered'] <= acs_df['Final Day to ENTER - 1 Day'], 'YES', 'NO')

In [22]:
acs_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2803 entries, 0 to 2802
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   DBN                         2803 non-null   object
 1   School Name                 2803 non-null   object
 2   OORS#                       2803 non-null   object
 3   Date                        2803 non-null   datetime64[ns]
 4   PrincInformed               2803 non-null   datetime64[ns]
 5   OccDateEntered              2803 non-null   datetime64[ns]
 6   PreparedBy                  2803 non-null   object
 7   PreparedByEmail             2292 non-null   object
 8   WhoSource                   2803 non-null   object
 9   Final Day to ENTER - 1 Day  2803 non-null   datetime64[ns]
 10  Entered on Time             2803 non-null   object
dtypes: datetime64[ns](4), object(7)
memory usage: 262.8+ KB

In [ ]:
#Export data to excel: https://datatofish.com/export-dataframe-to-excel/
#df.to_excel(r'Path to store the exported excel file\File Name.xlsx', sheet_name='Your sheet name', index = False)
#Formatting: https://xlsxwriter.readthedocs.io/working_with_pandas.html

#acs_df.to_excel(r"/Users/holly/Desktop/nycdoe/01142021 Compliance Data FINAL.xlsx", sheet_name='ACS',header=True, merge_cells=False, index=False)

**L1-5 INCIDENTS**

1. Import L1-5 Incident Data
2. Merge with All Dates -- Join on Date
3. Add Final Day to ENTER - 1 Day, 10 Days from All Dates table
4. Create field: Entered on Time: If OccDateEntered <= Final Day to Enter - 1 Day --> YES, otherwise, NO

In [23]:
inc_df = inc.merge(alldates, left_on='Date', right_on='Date', how='left')

In [24]:
inc_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4416 entries, 0 to 4415
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   DBN                         4416 non-null   object
 1   School Name                 4416 non-null   object
 2   Level                       4416 non-null   int64
 3   Code                        4416 non-null   object
 4   Short Description           4416 non-null   object
 5   OORS#                       4416 non-null   object
 6   Date                        4416 non-null   datetime64[ns]
 7   PrincInformed               4416 non-null   datetime64[ns]
 8   OccDateEntered              4416 non-null   datetime64[ns]
 9   Academic Year               4416 non-null   object
 10  PreparedBy                  4415 non-null   object
 11  PreparedByEmail             3551 non-null   object
 12  Location                    4416 non-null   object
 13  OccID                       4416 non-null   int64
 14  WhoSource                   4416 non-null   object
 15  Unnamed: 15                 31 non-null     object
 16  Day of Week                 4416 non-null   object
 17  School Day                  4416 non-null   object
 18  Nearest School Day          4416 non-null   datetime64[ns]
 19  Final Day to ENTER - 1 Day  4416 non-null   datetime64[ns]
 20  2 Days                      4416 non-null   datetime64[ns]
 21  5 Days                      4416 non-null   datetime64[ns]
 22  10 Days                     4416 non-null   datetime64[ns]
dtypes: datetime64[ns](8), int64(2), object(13)
memory usage: 828.0+ KB

In [25]:
inc_df['Entered on Time'] = np.where(inc_df['OccDateEntered'] <= inc_df['Final Day to ENTER - 1 Day'], 'YES', 'NO')

In [26]:
#Drop Day of Week, School Day, Nearest School Day, 2 Days, 5 Days

inc_df.drop('Academic Year', axis = 1, inplace = True)
inc_df.drop('PreparedBy', axis = 1, inplace = True)
inc_df.drop('PreparedByEmail', axis = 1, inplace = True)
inc_df.drop('OccID', axis = 1, inplace = True)
inc_df.drop('Day of Week', axis = 1, inplace = True)
inc_df.drop('School Day', axis = 1, inplace = True)
inc_df.drop('Nearest School Day', axis = 1, inplace = True)
inc_df.drop('2 Days', axis = 1, inplace = True)
inc_df.drop('5 Days', axis = 1, inplace = True)
inc_df.drop('10 Days', axis = 1, inplace = True)
inc_df.drop('Unnamed: 15', axis = 1, inplace = True)

In [27]:
inc_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4416 entries, 0 to 4415
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   DBN                         4416 non-null   object
 1   School Name                 4416 non-null   object
 2   Level                       4416 non-null   int64
 3   Code                        4416 non-null   object
 4   Short Description           4416 non-null   object
 5   OORS#                       4416 non-null   object
 6   Date                        4416 non-null   datetime64[ns]
 7   PrincInformed               4416 non-null   datetime64[ns]
 8   OccDateEntered              4416 non-null   datetime64[ns]
 9   Location                    4416 non-null   object
 10  WhoSource                   4416 non-null   object
 11  Final Day to ENTER - 1 Day  4416 non-null   datetime64[ns]
 12  Entered on Time             4416 non-null   object
dtypes: datetime64[ns](4), int64(1), object(8)
memory usage: 483.0+ KB

In [ ]:
#Export data to excel: https://datatofish.com/export-dataframe-to-excel/
#df.to_excel(r'Path to store the exported excel file\File Name.xlsx', sheet_name='Your sheet name', index = False)
#Formatting: https://xlsxwriter.readthedocs.io/working_with_pandas.html

#inc_df.to_excel(r"/Users/holly/Desktop/nycdoe/01142021 Compliance Data FINAL.xlsx", sheet_name='L1-5',header=True, merge_cells=False, index=False)

**MISSING STUDENTS**

1. Import Missing Incident Data
2. Merge with All Dates -- Join on Date
3. Remove duplicate records based on ControlNo
4. Add Final Day to ENTER - 1 Day, 10 Days from All Dates table
5. Create field: Entered on Time: If OccDateEntered <= Final Day to Enter - 1 Day --> YES, otherwise, NO

In [28]:
missing_df = missing.merge(alldates, left_on='Date', right_on='Date', how='left')

In [29]:
missing_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 54 entries, 0 to 53
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   RowNumber                   54 non-null     int64
 1   DBN                         54 non-null     object
 2   School Name                 54 non-null     object
 3   Academic Year               54 non-null     object
 4   AcademicYear                54 non-null     object
 5   ControlNo                   54 non-null     object
 6   ClassificationCode          54 non-null     object
 7   Short Description           54 non-null     object
 8   Date                        54 non-null     datetime64[ns]
 9   PrincInformed               54 non-null     datetime64[ns]
 10  OccDateEntered              54 non-null     datetime64[ns]
 11  Submitted                   54 non-null     bool
 12  UpdatedDate                 54 non-null     datetime64[ns]
 13  WhoSource                   54 non-null     object
 14  Day of Week                 54 non-null     object
 15  School Day                  54 non-null     object
 16  Nearest School Day          54 non-null     datetime64[ns]
 17  Final Day to ENTER - 1 Day  54 non-null     datetime64[ns]
 18  2 Days                      54 non-null     datetime64[ns]
 19  5 Days                      54 non-null     datetime64[ns]
 20  10 Days                     54 non-null     datetime64[ns]
dtypes: bool(1), datetime64[ns](9), int64(1), object(10)
memory usage: 8.9+ KB

In [30]:
#https://www.interviewqs.com/ddi-code-snippets/drop-duplicate-rows-pandas
missing_df = missing_df.drop_duplicates(subset='ControlNo', keep="first")

In [31]:
missing_df['Entered on Time'] = np.where(missing_df['OccDateEntered'] <= missing_df['Final Day to ENTER - 1 Day'], 'YES', 'NO')

In [32]:
#Drop Day of Week, School Day, Nearest School Day, 2 Days, 5 Days, 10 Days

missing_df.drop('Submitted', axis = 1, inplace = True)
missing_df.drop('UpdatedDate', axis = 1, inplace = True)
missing_df.drop('Day of Week', axis = 1, inplace = True)
missing_df.drop('School Day', axis = 1, inplace = True)
missing_df.drop('Nearest School Day', axis = 1, inplace = True)
missing_df.drop('2 Days', axis = 1, inplace = True)
missing_df.drop('5 Days', axis = 1, inplace = True)
missing_df.drop('10 Days', axis = 1, inplace = True)

In [33]:
missing_df.head()

,RowNumber,DBN,School Name,Academic Year,AcademicYear,ControlNo,ClassificationCode,Short Description,Date,PrincInformed,OccDateEntered,WhoSource,Final Day to ENTER - 1 Day,Entered on Time
0,1,07X522,Bronx Design and Construction Academy,2020-2021,2020-2021,07X522-101320-0003,B20,Leaving Class or School Premises w/o Permission,2020-10-13,2020-10-13,2020-10-13,CENTRAL\TLeonar,2020-10-14,YES
1,1,79M973,Restart Academy,2020-2021,2020-2021,79M973-100820-0009,N12,Missing child,2020-10-08,2020-10-14,2020-10-14,CENTRAL\JDhanpaul,2020-10-09,NO
2,1,79M973,Restart Academy,2020-2021,2020-2021,79M973-100820-0010,N12,Missing child,2020-10-08,2020-10-14,2020-10-14,CENTRAL\JDhanpaul,2020-10-09,NO
3,1,79M973,Restart Academy,2020-2021,2020-2021,79M973-100920-0011,B20,Leaving Class or School Premises w/o Permission,2020-10-09,2020-10-09,2020-10-14,CENTRAL\TLeonar,2020-10-13,NO
4,1,75M035,P.S. 035,2020-2021,2020-2021,75M035-100620-0009,B20,Leaving Class or School Premises w/o Permission,2020-10-06,2020-10-06,2020-10-14,CENTRAL\RDavid3,2020-10-07,NO

In [34]:
missing_df.shape

(43, 14)

In [ ]:
#Export data to excel: https://datatofish.com/export-dataframe-to-excel/
#df.to_excel(r'Path to store the exported excel file\File Name.xlsx', sheet_name='Your sheet name', index = False)
#Formatting: https://xlsxwriter.readthedocs.io/working_with_pandas.html

#missing_df.to_excel(r"/Users/holly/Desktop/nycdoe/01142021 Compliance Data FINAL.xlsx", sheet_name='Missing',header=True, merge_cells=False, index=False)

**MATERIAL INCIDENTS**

Import Material Incident Incident Data
1. Merge with All Dates -- Join on Date
2. Add Final Day to ENTER - 1 Day, 5 Days, 10 Days from All Dates table
3. Create field: Entered on Time: If OccDateEntered <= Final Day to Enter - 1 Day --> YES, otherwise, NO
4. Create field: Updated on Time: If Update Date <= 10 Days --> YES, otherwise, NO
5. Create field: Investigated on Time: If CRA832InitialInvestigationCompletionDate <= 5 Days --> YES, otherwise, NO

In [35]:
material_df = material.merge(alldates, left_on='Date', right_on='Date', how='left')

In [36]:
material_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1824 entries, 0 to 1823
Data columns (total 27 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   RowNumber                                 1824 non-null   int64
 1   AcademicYear                              1824 non-null   object
 2   DBN                                       1824 non-null   object
 3   School Name                               1824 non-null   object
 4   Classification_Code                       1824 non-null   object
 5   Short Description                         1824 non-null   object
 6   OccID                                     1824 non-null   int64
 7   OORS#                                     1824 non-null   object
 8   Date                                      1824 non-null   datetime64[ns]
 9   PrincInformed                             1824 non-null   datetime64[ns]
 10  Update Date                               1784 non-null   datetime64[ns]
 11  CRA832InitialInvestigationCompletionDate  1784 non-null   datetime64[ns]
 12  BiasRelated                               1824 non-null   bool
 13  MaterialIncidents                         1824 non-null   bool
 14  OccDateEntered                            1824 non-null   datetime64[ns]
 15  Cyberbullying                             1824 non-null   bool
 16  Harassment_Intimidation_Bullying          1824 non-null   bool
 17  MaterialSexualInNature                    1824 non-null   bool
 18  InvolveStudentOnStudentConduct            1824 non-null   bool
 19  CRA832ConductAViolation                   1824 non-null   bool
 20  Day of Week                               1824 non-null   object
 21  School Day                                1824 non-null   object
 22  Nearest School Day                        1824 non-null   datetime64[ns]
 23  Final Day to ENTER - 1 Day                1824 non-null   datetime64[ns]
 24  2 Days                                    1824 non-null   datetime64[ns]
 25  5 Days                                    1824 non-null   datetime64[ns]
 26  10 Days                                   1824 non-null   datetime64[ns]
dtypes: bool(7), datetime64[ns](10), int64(2), object(8)
memory usage: 311.7+ KB

In [37]:
material_df['Entered on Time'] = np.where(material_df['OccDateEntered'] <= material_df['Final Day to ENTER - 1 Day'], 'YES', 'NO')

In [38]:
material_df['Investigated on Time'] = np.where(material_df['CRA832InitialInvestigationCompletionDate'] <= material_df['5 Days'], 'YES', 'NO')

In [39]:
material_df['Investigated on Time'] = np.where(material_df['CRA832InitialInvestigationCompletionDate'].isnull(), ' ', material_df['Investigated on Time'])

In [40]:
material_df['Updated on Time'] = np.where(material_df['Update Date'] <= material_df['10 Days'], 'YES', 'NO')

In [41]:
material_df['Updated on Time'] = np.where(material_df['Update Date'].isnull(), ' ', material_df['Updated on Time'])

In [42]:
#Drop Day of Week, School Day, Nearest School Day, 2 Days, 5 Days

material_df.drop('OccID', axis = 1, inplace = True)
material_df.drop('Harassment_Intimidation_Bullying', axis = 1, inplace = True)
material_df.drop('MaterialSexualInNature', axis = 1, inplace = True)
material_df.drop('Cyberbullying', axis = 1, inplace = True)
material_df.drop('MaterialIncidents', axis = 1, inplace = True)
material_df.drop('BiasRelated', axis = 1, inplace = True)
material_df.drop('Day of Week', axis = 1, inplace = True)
material_df.drop('School Day', axis = 1, inplace = True)
material_df.drop('Nearest School Day', axis = 1, inplace = True)
material_df.drop('2 Days', axis = 1, inplace = True)

In [43]:
material_df.head()

,RowNumber,AcademicYear,DBN,School Name,Classification_Code,Short Description,OORS#,Date,PrincInformed,Update Date,CRA832InitialInvestigationCompletionDate,OccDateEntered,InvolveStudentOnStudentConduct,CRA832ConductAViolation,Final Day to ENTER - 1 Day,5 Days,10 Days,Entered on Time,Investigated on Time,Updated on Time
0,1,2020-2021,26Q067,J.H.S. 067 Louis Pasteur,B23,Using Slurs (Bias),26Q067-071820-0001,2020-07-18,2020-07-21,2020-07-23,2020-07-23,2020-07-23,True,True,2020-07-20,2020-07-24,2020-08-03,NO,YES,YES
1,1,2020-2021,13K430,Brooklyn Technical High School,B34,Sexually Suggestive (Verbal/Physical),13K430-072820-0004,2020-07-28,2020-08-03,2020-08-12,2020-08-12,2020-08-03,True,True,2020-07-29,2020-08-05,2020-08-12,NO,NO,YES
2,1,2020-2021,31R440,New Dorp High School,B15,"Profane, Obscene, Vulgar Language or Gestures",31R440-091020-0003,2020-09-10,2020-09-10,2020-09-21,2020-09-21,2020-09-10,True,False,2020-09-11,2020-09-17,2020-09-24,YES,NO,YES
3,1,2020-2021,02M475,Stuyvesant High School,B23,Using Slurs (Bias),02M475-091620-0010,2020-09-16,2020-09-16,2020-12-04,2020-12-04,2020-09-16,True,False,2020-09-17,2020-09-23,2020-10-01,YES,NO,NO
4,1,2020-2021,22K425,James Madison High School,B35,Posting/Distributing Literature or Material Co...,22K425-091620-0002,2020-09-16,2020-09-16,2020-09-18,2020-09-18,2020-09-16,True,False,2020-09-17,2020-09-23,2020-10-01,YES,YES,YES

In [ ]:
#Export data to excel: https://datatofish.com/export-dataframe-to-excel/
#df.to_excel(r'Path to store the exported excel file\File Name.xlsx', sheet_name='Your sheet name', index = False)
#Formatting: https://xlsxwriter.readthedocs.io/working_with_pandas.html

#material_df.to_excel(r"/Users/holly/Desktop/nycdoe/01142021 Compliance Data FINAL.xlsx", sheet_name='Material',header=True, merge_cells=False, index=False)

In [46]:
#Source: https://xlsxwriter.readthedocs.io/example_pandas_multiple.html

writer = pd.ExcelWriter('/Users/holly/Desktop/nycdoe/01142021 Compliance Data FINAL.xlsx', engine='xlsxwriter')

ideation_df.to_excel(writer, sheet_name='Ideation')
acs_df.to_excel(writer, sheet_name='ACS')
inc_df.to_excel(writer, sheet_name='L1-5')
missing_df.to_excel(writer, sheet_name='Missing')
material_df.to_excel(writer, sheet_name='Material')

writer.save()