# Compliance Data  -- Monthly Report

In [1]:
import pandas as pd
import numpy as np

In [2]:
###Import data
##1. Find file in finder
##2. Option + Command + C
##3. Paste Info read_csv(r” ”)

#Data file merges with All Dates when all data is saved from Access. When saved from SQL, the data does not merge accurately.

df = pd.ExcelFile(r"/Users/holly/Desktop/nycdoe/01262021 Compliance Data for HB.xlsx")

In [3]:
#Read data from corrrect tab.

ideation = df.parse('Ideation')
acs = df.parse('ACS')
missing = df.parse('MISSING')
inc = df.parse('L1-5')
material = df.parse('Material')
alldates = df.parse('All Dates')

In [4]:
alldates.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        365 non-null    datetime64[ns]
 1   Day of Week                 365 non-null    object
 2   School Day                  365 non-null    object
 3   Nearest School Day          365 non-null    datetime64[ns]
 4   Final Day to ENTER - 1 Day  365 non-null    datetime64[ns]
 5   2 Days                      365 non-null    datetime64[ns]
 6   5 Days                      365 non-null    datetime64[ns]
 7   10 Days                     365 non-null    datetime64[ns]
dtypes: datetime64[ns](6), object(2)
memory usage: 22.9+ KB

**SUICIDE IDEATION**

1. Import Incident Data
2. Merge with All Dates -- Join on Data
3. Add Final Day to ENTER - 1 Day, 10 Days from All Dates table
4. Create field: Entered on Time: If OccDateEntered <= Final Day to Enter - 1 Day --> YES, otherwise, NO
5. Create field: Updated on Time: If Updated Date <= 10 Days --> YES, otherwise, NO
6. If Updated Data is Blank, leave Updated on Time Blank.

In [5]:
#schools_susptype = schools.merge(susptypefinal, left_on='DBN', right_on='ATS', how='left')
ideation_df = ideation.merge(alldates, left_on='Date', right_on='Date', how='left')

In [6]:
#schools_susptype.drop('ATS', axis = 1, inplace = True)
#Drop Day of Week, School Day, Nearest School Day, 2 Days, 5 Days
ideation_df.drop('Day of Week', axis = 1, inplace = True)
ideation_df.drop('School Day', axis = 1, inplace = True)
ideation_df.drop('Nearest School Day', axis = 1, inplace = True)
ideation_df.drop('2 Days', axis = 1, inplace = True)
ideation_df.drop('5 Days', axis = 1, inplace = True)
ideation_df.drop('UpdatedText', axis = 1, inplace = True)
ideation_df.drop('EventType', axis = 1, inplace = True)

In [7]:
ideation_df

,RowNumber,AcademicYear,ATS,School Name,ControlNo,Code,EIC,Date,PrincInformed,OccDateEntered,Updated Date,WhoSource,Final Day to ENTER - 1 Day,10 Days
0,1,2020-2021,01M020,P.S. 020 Anna Silver,01M020-111020-0009,O57,False,2020-11-10,2020-11-10,2020-11-10,2020-11-13,CENTRAL\JEspinobarros2,2020-11-12,2020-11-25
1,1,2020-2021,01M020,P.S. 020 Anna Silver,01M020-102320-0004,O57,False,2020-10-23,2020-10-23,2020-10-26,2020-10-26,CENTRAL\JEspinobarros2,2020-10-26,2020-11-06
2,1,2020-2021,01M034,P.S. 034 Franklin D. Roosevelt,01M034-122920-0005,O57,False,2020-12-29,2021-01-04,2021-01-07,2021-01-07,CENTRAL\BGlover,2021-01-04,2021-01-15
3,1,2020-2021,01M034,P.S. 034 Franklin D. Roosevelt,01M034-121120-0003,O57,False,2020-12-11,2020-12-11,2020-12-11,2020-12-11,CENTRAL\BGlover,2020-12-14,2021-01-05
4,1,2020-2021,01M064,P.S. 064 Robert Simon,01M064-111820-0005,O57,False,2020-11-18,2020-11-18,2020-11-19,2020-12-01,CENTRAL\CJavier4,2020-11-19,2020-12-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1467,1,2020-2021,96M000,Manhattan ISC,96M000-072020-0026,O57,False,2020-07-20,2020-07-20,2020-07-22,2020-07-23,CENTRAL\SGumbs4,2020-07-21,2020-08-04
1468,1,2020-2021,96M000,Manhattan ISC,96M000-072820-0043,O57,True,2020-07-28,2020-07-28,2020-07-29,2020-08-06,CENTRAL\SSimmon2,2020-07-29,2020-08-12
1469,1,2020-2021,96M000,Manhattan ISC,96M000-072820-0055,O57,False,2020-07-28,2020-07-28,2020-08-06,2020-08-06,CENTRAL\SGumbs4,2020-07-29,2020-08-12
1470,1,2020-2021,96MD75,District 75,96MD75-110420-0027,O57,True,2020-11-04,2020-11-04,2020-11-16,2020-11-16,CENTRAL\RDavid3,2020-11-05,2020-11-19
1471,1,2020-2021,96MD75,District 75,96MD75-100620-0013,O57,True,2020-10-06,2020-10-06,2020-10-06,2020-10-06,CENTRAL\TLeonar,2020-10-07,2020-10-21

In [8]:
#Create fileds: Entered on Time: If OccDateEntered <= Final Day to Enter - 1 Day --> YES, otherwise, NO
#Source: https://www.geeksforgeeks.org/python-creating-a-pandas-dataframe-column-based-on-a-given-condition/
#df['hasimage'] = np.where(df['photos']!= '[]', True, False)  
#Source: https://www.dataquest.io/blog/tutorial-add-column-pandas-dataframe-based-on-if-else-condition/
#df['Price'] = [1500 if x =='Music' else 800 for x in df['Event']] 

ideation_df['Entered on Time'] = np.where(ideation_df['PrincInformed'] <= ideation_df['Final Day to ENTER - 1 Day'], 'YES', 'NO')

In [9]:
ideation_df

,RowNumber,AcademicYear,ATS,School Name,ControlNo,Code,EIC,Date,PrincInformed,OccDateEntered,Updated Date,WhoSource,Final Day to ENTER - 1 Day,10 Days,Entered on Time
0,1,2020-2021,01M020,P.S. 020 Anna Silver,01M020-111020-0009,O57,False,2020-11-10,2020-11-10,2020-11-10,2020-11-13,CENTRAL\JEspinobarros2,2020-11-12,2020-11-25,YES
1,1,2020-2021,01M020,P.S. 020 Anna Silver,01M020-102320-0004,O57,False,2020-10-23,2020-10-23,2020-10-26,2020-10-26,CENTRAL\JEspinobarros2,2020-10-26,2020-11-06,YES
2,1,2020-2021,01M034,P.S. 034 Franklin D. Roosevelt,01M034-122920-0005,O57,False,2020-12-29,2021-01-04,2021-01-07,2021-01-07,CENTRAL\BGlover,2021-01-04,2021-01-15,YES
3,1,2020-2021,01M034,P.S. 034 Franklin D. Roosevelt,01M034-121120-0003,O57,False,2020-12-11,2020-12-11,2020-12-11,2020-12-11,CENTRAL\BGlover,2020-12-14,2021-01-05,YES
4,1,2020-2021,01M064,P.S. 064 Robert Simon,01M064-111820-0005,O57,False,2020-11-18,2020-11-18,2020-11-19,2020-12-01,CENTRAL\CJavier4,2020-11-19,2020-12-04,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1467,1,2020-2021,96M000,Manhattan ISC,96M000-072020-0026,O57,False,2020-07-20,2020-07-20,2020-07-22,2020-07-23,CENTRAL\SGumbs4,2020-07-21,2020-08-04,YES
1468,1,2020-2021,96M000,Manhattan ISC,96M000-072820-0043,O57,True,2020-07-28,2020-07-28,2020-07-29,2020-08-06,CENTRAL\SSimmon2,2020-07-29,2020-08-12,YES
1469,1,2020-2021,96M000,Manhattan ISC,96M000-072820-0055,O57,False,2020-07-28,2020-07-28,2020-08-06,2020-08-06,CENTRAL\SGumbs4,2020-07-29,2020-08-12,YES
1470,1,2020-2021,96MD75,District 75,96MD75-110420-0027,O57,True,2020-11-04,2020-11-04,2020-11-16,2020-11-16,CENTRAL\RDavid3,2020-11-05,2020-11-19,YES
1471,1,2020-2021,96MD75,District 75,96MD75-100620-0013,O57,True,2020-10-06,2020-10-06,2020-10-06,2020-10-06,CENTRAL\TLeonar,2020-10-07,2020-10-21,YES

In [10]:
ideation_df['Updated on Time'] = np.where(ideation_df['Updated Date'] <= ideation_df['10 Days'], 'YES', 'NO')

In [11]:
ideation_df

,RowNumber,AcademicYear,ATS,School Name,ControlNo,Code,EIC,Date,PrincInformed,OccDateEntered,Updated Date,WhoSource,Final Day to ENTER - 1 Day,10 Days,Entered on Time,Updated on Time
0,1,2020-2021,01M020,P.S. 020 Anna Silver,01M020-111020-0009,O57,False,2020-11-10,2020-11-10,2020-11-10,2020-11-13,CENTRAL\JEspinobarros2,2020-11-12,2020-11-25,YES,YES
1,1,2020-2021,01M020,P.S. 020 Anna Silver,01M020-102320-0004,O57,False,2020-10-23,2020-10-23,2020-10-26,2020-10-26,CENTRAL\JEspinobarros2,2020-10-26,2020-11-06,YES,YES
2,1,2020-2021,01M034,P.S. 034 Franklin D. Roosevelt,01M034-122920-0005,O57,False,2020-12-29,2021-01-04,2021-01-07,2021-01-07,CENTRAL\BGlover,2021-01-04,2021-01-15,YES,YES
3,1,2020-2021,01M034,P.S. 034 Franklin D. Roosevelt,01M034-121120-0003,O57,False,2020-12-11,2020-12-11,2020-12-11,2020-12-11,CENTRAL\BGlover,2020-12-14,2021-01-05,YES,YES
4,1,2020-2021,01M064,P.S. 064 Robert Simon,01M064-111820-0005,O57,False,2020-11-18,2020-11-18,2020-11-19,2020-12-01,CENTRAL\CJavier4,2020-11-19,2020-12-04,YES,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1467,1,2020-2021,96M000,Manhattan ISC,96M000-072020-0026,O57,False,2020-07-20,2020-07-20,2020-07-22,2020-07-23,CENTRAL\SGumbs4,2020-07-21,2020-08-04,YES,YES
1468,1,2020-2021,96M000,Manhattan ISC,96M000-072820-0043,O57,True,2020-07-28,2020-07-28,2020-07-29,2020-08-06,CENTRAL\SSimmon2,2020-07-29,2020-08-12,YES,YES
1469,1,2020-2021,96M000,Manhattan ISC,96M000-072820-0055,O57,False,2020-07-28,2020-07-28,2020-08-06,2020-08-06,CENTRAL\SGumbs4,2020-07-29,2020-08-12,YES,YES
1470,1,2020-2021,96MD75,District 75,96MD75-110420-0027,O57,True,2020-11-04,2020-11-04,2020-11-16,2020-11-16,CENTRAL\RDavid3,2020-11-05,2020-11-19,YES,YES
1471,1,2020-2021,96MD75,District 75,96MD75-100620-0013,O57,True,2020-10-06,2020-10-06,2020-10-06,2020-10-06,CENTRAL\TLeonar,2020-10-07,2020-10-21,YES,YES

In [12]:
#Updated on Time: If Updated Date <= 10 Days --> YES, otherwise, NO
#ideation_df['Entered on Time'] = np.where(ideation_df['OccDateEntered'] <= ideation_df['Final Day to ENTER - 1 Day'], 'YES', 'NO')
ideation_df['Updated on Time'] = np.where(ideation_df['Updated Date'].isnull(), ' ', ideation_df['Updated on Time'])

In [13]:
ideation_df

,RowNumber,AcademicYear,ATS,School Name,ControlNo,Code,EIC,Date,PrincInformed,OccDateEntered,Updated Date,WhoSource,Final Day to ENTER - 1 Day,10 Days,Entered on Time,Updated on Time
0,1,2020-2021,01M020,P.S. 020 Anna Silver,01M020-111020-0009,O57,False,2020-11-10,2020-11-10,2020-11-10,2020-11-13,CENTRAL\JEspinobarros2,2020-11-12,2020-11-25,YES,YES
1,1,2020-2021,01M020,P.S. 020 Anna Silver,01M020-102320-0004,O57,False,2020-10-23,2020-10-23,2020-10-26,2020-10-26,CENTRAL\JEspinobarros2,2020-10-26,2020-11-06,YES,YES
2,1,2020-2021,01M034,P.S. 034 Franklin D. Roosevelt,01M034-122920-0005,O57,False,2020-12-29,2021-01-04,2021-01-07,2021-01-07,CENTRAL\BGlover,2021-01-04,2021-01-15,YES,YES
3,1,2020-2021,01M034,P.S. 034 Franklin D. Roosevelt,01M034-121120-0003,O57,False,2020-12-11,2020-12-11,2020-12-11,2020-12-11,CENTRAL\BGlover,2020-12-14,2021-01-05,YES,YES
4,1,2020-2021,01M064,P.S. 064 Robert Simon,01M064-111820-0005,O57,False,2020-11-18,2020-11-18,2020-11-19,2020-12-01,CENTRAL\CJavier4,2020-11-19,2020-12-04,YES,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1467,1,2020-2021,96M000,Manhattan ISC,96M000-072020-0026,O57,False,2020-07-20,2020-07-20,2020-07-22,2020-07-23,CENTRAL\SGumbs4,2020-07-21,2020-08-04,YES,YES
1468,1,2020-2021,96M000,Manhattan ISC,96M000-072820-0043,O57,True,2020-07-28,2020-07-28,2020-07-29,2020-08-06,CENTRAL\SSimmon2,2020-07-29,2020-08-12,YES,YES
1469,1,2020-2021,96M000,Manhattan ISC,96M000-072820-0055,O57,False,2020-07-28,2020-07-28,2020-08-06,2020-08-06,CENTRAL\SGumbs4,2020-07-29,2020-08-12,YES,YES
1470,1,2020-2021,96MD75,District 75,96MD75-110420-0027,O57,True,2020-11-04,2020-11-04,2020-11-16,2020-11-16,CENTRAL\RDavid3,2020-11-05,2020-11-19,YES,YES
1471,1,2020-2021,96MD75,District 75,96MD75-100620-0013,O57,True,2020-10-06,2020-10-06,2020-10-06,2020-10-06,CENTRAL\TLeonar,2020-10-07,2020-10-21,YES,YES

In [14]:
#Export data to excel: https://datatofish.com/export-dataframe-to-excel/
#df.to_excel(r'Path to store the exported excel file\File Name.xlsx', sheet_name='Your sheet name', index = False)
#Formatting: https://xlsxwriter.readthedocs.io/working_with_pandas.html

#ideation_df.to_excel(r"/Users/holly/Desktop/nycdoe/01142021 Compliance Data FINAL.xlsx", sheet_name='Ideation',header=True, merge_cells=False, index=False)

**ACS**

1. Import ACS Data
2. Merge with All Dates -- Join on Date
3. Add Final Day to ENTER - 1 Day, 10 Days from All Dates table
4. Create field: Entered on Time: If OccDateEntered <= Final Day to Enter - 1 Day --> YES, otherwise, NO

In [20]:
acs_df = acs.merge(alldates, left_on='Date', right_on='Date', how='left')

In [21]:
acs_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2882 entries, 0 to 2881
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   DBN                         2882 non-null   object
 1   School Name                 2882 non-null   object
 2   Code                        2882 non-null   object
 3   EIC                         2882 non-null   bool
 4   OORS#                       2882 non-null   object
 5   Date                        2882 non-null   datetime64[ns]
 6   PrincInformed               2882 non-null   datetime64[ns]
 7   OccDateEntered              2882 non-null   datetime64[ns]
 8   Academic Year               2882 non-null   object
 9   PreparedBy                  2882 non-null   object
 10  PreparedByEmail             2356 non-null   object
 11  WhoSource                   2882 non-null   object
 12  EventType                   2882 non-null   object
 13  Day of Week                 2882 non-null   object
 14  School Day                  2882 non-null   object
 15  Nearest School Day          2882 non-null   datetime64[ns]
 16  Final Day to ENTER - 1 Day  2882 non-null   datetime64[ns]
 17  2 Days                      2882 non-null   datetime64[ns]
 18  5 Days                      2882 non-null   datetime64[ns]
 19  10 Days                     2882 non-null   datetime64[ns]
dtypes: bool(1), datetime64[ns](8), object(11)
memory usage: 453.1+ KB

In [22]:
acs_df.tail()

,DBN,School Name,Code,EIC,OORS#,Date,PrincInformed,OccDateEntered,Academic Year,PreparedBy,PreparedByEmail,WhoSource,EventType,Day of Week,School Day,Nearest School Day,Final Day to ENTER - 1 Day,2 Days,5 Days,10 Days
2877,96M000,Manhattan ISC,O77,False,96M000-082820-0077,2020-08-28,2020-08-28,2020-09-01,2020-2021,Timothy Evans,TEvans7@schools.nyc.gov,CENTRAL\SGumbs4,Entered,Friday,No,2020-09-16,2020-08-31,2020-09-01,2020-09-04,2020-09-11
2878,96Q04M,Queens ISC,O77,False,96Q04M-071420-0026,2020-07-14,2020-07-14,2020-07-21,2020-2021,Thadia Louis,TLouis@schools.nyc.gov,CENTRAL\SGumbs4,Entered,Tuesday,Yes,2020-07-14,2020-07-15,2020-07-16,2020-07-21,2020-07-28
2879,96Q04M,Queens ISC,O77,False,96Q04M-080420-0068,2020-08-04,2020-08-04,2020-08-06,2020-2021,Lauren Keenan,LKeenan4@schools.nyc.gov,CENTRAL\SGumbs4,Entered,Tuesday,Yes,2020-08-04,2020-08-05,2020-08-06,2020-08-11,2020-08-18
2880,96Q04M,Queens ISC,O77,False,96Q04M-080320-0069,2020-08-03,2020-08-03,2020-08-06,2020-2021,Sharmayne Witherspoon,SWitherspoon@schools.nyc.gov,CENTRAL\SGumbs4,Entered,Monday,Yes,2020-08-03,2020-08-04,2020-08-05,2020-08-10,2020-08-17
2881,96R00M,Staten Island ISC,O77,False,96R00M-070820-0014,2020-07-08,2020-07-08,2020-07-16,2020-2021,Marygrace DiForte,NaN,CENTRAL\TPeele,Entered,Wednesday,Yes,2020-07-08,2020-07-09,2020-07-10,2020-07-15,2020-07-22

In [23]:
#Drop Day of Week, School Day, Nearest School Day, 2 Days, 5 Days
acs_df.drop('Code', axis = 1, inplace = True)
acs_df.drop('EIC', axis = 1, inplace = True)
acs_df.drop('Academic Year', axis = 1, inplace = True)
acs_df.drop('EventType', axis = 1, inplace = True)
acs_df.drop('Day of Week', axis = 1, inplace = True)
acs_df.drop('School Day', axis = 1, inplace = True)
acs_df.drop('Nearest School Day', axis = 1, inplace = True)
acs_df.drop('2 Days', axis = 1, inplace = True)
acs_df.drop('5 Days', axis = 1, inplace = True)
acs_df.drop('10 Days', axis = 1, inplace = True)
#acs_df.drop('Unnamed: 13', axis = 1, inplace = True)

In [24]:
acs_df.head()

,DBN,School Name,OORS#,Date,PrincInformed,OccDateEntered,PreparedBy,PreparedByEmail,WhoSource,Final Day to ENTER - 1 Day
0,01M019,P.S. 019 Asher Levy,01M019-100720-0005,2020-10-07,2020-10-07,2020-10-07,Cindy Lerner,clerner2@schools.nyc.gov,CENTRAL\CLerner2,2020-10-08
1,01M019,P.S. 019 Asher Levy,01M019-102320-0007,2020-10-23,2020-10-23,2020-10-23,Cindy Lerner,clerner2@schools.nyc.gov,CENTRAL\CLerner2,2020-10-26
2,01M019,P.S. 019 Asher Levy,01M019-110220-0010,2020-11-02,2020-11-02,2020-11-02,Cindy Lerner,clerner2@schools.nyc.gov,CENTRAL\CLerner2,2020-11-03
3,01M019,P.S. 019 Asher Levy,01M019-120320-0011,2020-12-03,2020-12-03,2020-12-03,Cindy Lerner,clerner2@schools.nyc.gov,CENTRAL\CLerner2,2020-12-04
4,01M020,P.S. 020 Anna Silver,01M020-101320-0002,2020-10-13,2020-10-13,2020-10-14,Jessica Espinobarros,jespinobarros2@schools.nyc.gov,CENTRAL\JEspinobarros2,2020-10-14

In [25]:
acs_df['Entered on Time'] = np.where(acs_df['PrincInformed'] <= acs_df['Final Day to ENTER - 1 Day'], 'YES', 'NO')

In [26]:
acs_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2882 entries, 0 to 2881
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   DBN                         2882 non-null   object
 1   School Name                 2882 non-null   object
 2   OORS#                       2882 non-null   object
 3   Date                        2882 non-null   datetime64[ns]
 4   PrincInformed               2882 non-null   datetime64[ns]
 5   OccDateEntered              2882 non-null   datetime64[ns]
 6   PreparedBy                  2882 non-null   object
 7   PreparedByEmail             2356 non-null   object
 8   WhoSource                   2882 non-null   object
 9   Final Day to ENTER - 1 Day  2882 non-null   datetime64[ns]
 10  Entered on Time             2882 non-null   object
dtypes: datetime64[ns](4), object(7)
memory usage: 270.2+ KB

In [27]:
#Export data to excel: https://datatofish.com/export-dataframe-to-excel/
#df.to_excel(r'Path to store the exported excel file\File Name.xlsx', sheet_name='Your sheet name', index = False)
#Formatting: https://xlsxwriter.readthedocs.io/working_with_pandas.html

#acs_df.to_excel(r"/Users/holly/Desktop/nycdoe/01142021 Compliance Data FINAL.xlsx", sheet_name='ACS',header=True, merge_cells=False, index=False)

**L1-5 INCIDENTS**

1. Import L1-5 Incident Data
2. Merge with All Dates -- Join on Date
3. Add Final Day to ENTER - 1 Day, 10 Days from All Dates table
4. Create field: Entered on Time: If OccDateEntered <= Final Day to Enter - 1 Day --> YES, otherwise, NO

In [28]:
inc_df = inc.merge(alldates, left_on='Date', right_on='Date', how='left')

In [29]:
inc_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4542 entries, 0 to 4541
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   DBN                         4542 non-null   object
 1   School Name                 4542 non-null   object
 2   Level                       4542 non-null   int64
 3   Code                        4542 non-null   object
 4   Short Description           4542 non-null   object
 5   OORS#                       4542 non-null   object
 6   Date                        4542 non-null   datetime64[ns]
 7   PrincInformed               4542 non-null   datetime64[ns]
 8   OccDateEntered              4542 non-null   datetime64[ns]
 9   Academic Year               4542 non-null   object
 10  PreparedBy                  4541 non-null   object
 11  PreparedByEmail             3658 non-null   object
 12  Location                    4542 non-null   object
 13  OccID                       4542 non-null   int64
 14  WhoSource                   4542 non-null   object
 15  Day of Week                 4542 non-null   object
 16  School Day                  4542 non-null   object
 17  Nearest School Day          4542 non-null   datetime64[ns]
 18  Final Day to ENTER - 1 Day  4542 non-null   datetime64[ns]
 19  2 Days                      4542 non-null   datetime64[ns]
 20  5 Days                      4542 non-null   datetime64[ns]
 21  10 Days                     4542 non-null   datetime64[ns]
dtypes: datetime64[ns](8), int64(2), object(12)
memory usage: 816.1+ KB

In [30]:
inc_df['Entered on Time'] = np.where(inc_df['OccDateEntered'] <= inc_df['Final Day to ENTER - 1 Day'], 'YES', 'NO')

In [31]:
#Drop Day of Week, School Day, Nearest School Day, 2 Days, 5 Days

inc_df.drop('Academic Year', axis = 1, inplace = True)
inc_df.drop('PreparedBy', axis = 1, inplace = True)
inc_df.drop('PreparedByEmail', axis = 1, inplace = True)
inc_df.drop('OccID', axis = 1, inplace = True)
inc_df.drop('Day of Week', axis = 1, inplace = True)
inc_df.drop('School Day', axis = 1, inplace = True)
inc_df.drop('Nearest School Day', axis = 1, inplace = True)
inc_df.drop('2 Days', axis = 1, inplace = True)
inc_df.drop('5 Days', axis = 1, inplace = True)
inc_df.drop('10 Days', axis = 1, inplace = True)
#inc_df.drop('Unnamed: 15', axis = 1, inplace = True)

In [32]:
inc_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4542 entries, 0 to 4541
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   DBN                         4542 non-null   object
 1   School Name                 4542 non-null   object
 2   Level                       4542 non-null   int64
 3   Code                        4542 non-null   object
 4   Short Description           4542 non-null   object
 5   OORS#                       4542 non-null   object
 6   Date                        4542 non-null   datetime64[ns]
 7   PrincInformed               4542 non-null   datetime64[ns]
 8   OccDateEntered              4542 non-null   datetime64[ns]
 9   Location                    4542 non-null   object
 10  WhoSource                   4542 non-null   object
 11  Final Day to ENTER - 1 Day  4542 non-null   datetime64[ns]
 12  Entered on Time             4542 non-null   object
dtypes: datetime64[ns](4), int64(1), object(8)
memory usage: 496.8+ KB

In [33]:
#Export data to excel: https://datatofish.com/export-dataframe-to-excel/
#df.to_excel(r'Path to store the exported excel file\File Name.xlsx', sheet_name='Your sheet name', index = False)
#Formatting: https://xlsxwriter.readthedocs.io/working_with_pandas.html

#inc_df.to_excel(r"/Users/holly/Desktop/nycdoe/01142021 Compliance Data FINAL.xlsx", sheet_name='L1-5',header=True, merge_cells=False, index=False)

**MISSING STUDENTS**

1. Import Missing Incident Data
2. Merge with All Dates -- Join on Date
3. Remove duplicate records based on ControlNo
4. Add Final Day to ENTER - 1 Day, 10 Days from All Dates table
5. Create field: Entered on Time: If OccDateEntered <= Final Day to Enter - 1 Day --> YES, otherwise, NO

In [34]:
missing_df = missing.merge(alldates, left_on='Date', right_on='Date', how='left')

In [35]:
missing_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 53 entries, 0 to 52
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   RowNumber                   53 non-null     int64
 1   DBN                         53 non-null     object
 2   School Name                 53 non-null     object
 3   Academic Year               53 non-null     object
 4   AcademicYear                53 non-null     object
 5   ControlNo                   53 non-null     object
 6   ClassificationCode          53 non-null     object
 7   Short Description           53 non-null     object
 8   Date                        53 non-null     datetime64[ns]
 9   PrincInformed               53 non-null     datetime64[ns]
 10  OccDateEntered              53 non-null     datetime64[ns]
 11  Submitted                   53 non-null     bool
 12  UpdatedDate                 53 non-null     datetime64[ns]
 13  WhoSource                   53 non-null     object
 14  Day of Week                 53 non-null     object
 15  School Day                  53 non-null     object
 16  Nearest School Day          53 non-null     datetime64[ns]
 17  Final Day to ENTER - 1 Day  53 non-null     datetime64[ns]
 18  2 Days                      53 non-null     datetime64[ns]
 19  5 Days                      53 non-null     datetime64[ns]
 20  10 Days                     53 non-null     datetime64[ns]
dtypes: bool(1), datetime64[ns](9), int64(1), object(10)
memory usage: 8.7+ KB

In [36]:
#https://www.interviewqs.com/ddi-code-snippets/drop-duplicate-rows-pandas
missing_df = missing_df.drop_duplicates(subset='ControlNo', keep="first")

In [37]:
missing_df['Entered on Time'] = np.where(missing_df['PrincInformed'] <= missing_df['Final Day to ENTER - 1 Day'], 'YES', 'NO')

In [38]:
#Drop Day of Week, School Day, Nearest School Day, 2 Days, 5 Days, 10 Days

missing_df.drop('Submitted', axis = 1, inplace = True)
missing_df.drop('UpdatedDate', axis = 1, inplace = True)
missing_df.drop('Day of Week', axis = 1, inplace = True)
missing_df.drop('School Day', axis = 1, inplace = True)
missing_df.drop('Nearest School Day', axis = 1, inplace = True)
missing_df.drop('2 Days', axis = 1, inplace = True)
missing_df.drop('5 Days', axis = 1, inplace = True)
missing_df.drop('10 Days', axis = 1, inplace = True)

In [39]:
missing_df.head()

,RowNumber,DBN,School Name,Academic Year,AcademicYear,ControlNo,ClassificationCode,Short Description,Date,PrincInformed,OccDateEntered,WhoSource,Final Day to ENTER - 1 Day,Entered on Time
0,1,07X522,Bronx Design and Construction Academy,2020-2021,2020-2021,07X522-101320-0003,B20,Leaving Class or School Premises w/o Permission,2020-10-13,2020-10-13,2020-10-13,CENTRAL\TLeonar,2020-10-14,YES
1,1,07X522,Bronx Design and Construction Academy,2020-2021,2020-2021,07X522-110420-0007,B20,Leaving Class or School Premises w/o Permission,2020-11-04,2020-11-04,2020-11-04,CENTRAL\JDhanpaul,2020-11-05,YES
2,1,07X522,Bronx Design and Construction Academy,2020-2021,2020-2021,07X522-100620-0002,B20,Leaving Class or School Premises w/o Permission,2020-10-06,2020-10-06,2020-10-06,CENTRAL\GRenschak,2020-10-07,YES
3,1,08X376,Antonia Pantoja Preparatory Academy: A College...,2020-2021,2020-2021,08X376-110420-0012,B20,Leaving Class or School Premises w/o Permission,2020-11-04,2020-11-04,2020-11-04,CENTRAL\DGuridy,2020-11-05,YES
4,1,10X353,World View High School,2020-2021,2020-2021,10X353-102320-0020,B20,Leaving Class or School Premises w/o Permission,2020-10-23,2020-10-23,2020-10-23,CENTRAL\TLeonar,2020-10-26,YES

In [40]:
missing_df.shape

(48, 14)

In [41]:
#Export data to excel: https://datatofish.com/export-dataframe-to-excel/
#df.to_excel(r'Path to store the exported excel file\File Name.xlsx', sheet_name='Your sheet name', index = False)
#Formatting: https://xlsxwriter.readthedocs.io/working_with_pandas.html

#missing_df.to_excel(r"/Users/holly/Desktop/nycdoe/01142021 Compliance Data FINAL.xlsx", sheet_name='Missing',header=True, merge_cells=False, index=False)

**MATERIAL INCIDENTS**

Import Material Incident Incident Data
1. Merge with All Dates -- Join on Date
2. Add Final Day to ENTER - 1 Day, 5 Days, 10 Days from All Dates table
3. Create field: Entered on Time: If OccDateEntered <= Final Day to Enter - 1 Day --> YES, otherwise, NO
4. Create field: Updated on Time: If Update Date <= 10 Days --> YES, otherwise, NO
5. Create field: Investigated on Time: If CRA832InitialInvestigationCompletionDate <= 5 Days --> YES, otherwise, NO

In [42]:
material_df = material.merge(alldates, left_on='Date', right_on='Date', how='left')

In [43]:
material_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1871 entries, 0 to 1870
Data columns (total 27 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   RowNumber                                 1871 non-null   int64
 1   AcademicYear                              1871 non-null   object
 2   DBN                                       1871 non-null   object
 3   School Name                               1871 non-null   object
 4   Classification_Code                       1871 non-null   object
 5   Short Description                         1871 non-null   object
 6   OccID                                     1871 non-null   int64
 7   OORS#                                     1871 non-null   object
 8   Date                                      1871 non-null   datetime64[ns]
 9   PrincInformed                             1871 non-null   datetime64[ns]
 10  Update Date                               1821 non-null   datetime64[ns]
 11  CRA832InitialInvestigationCompletionDate  1821 non-null   datetime64[ns]
 12  BiasRelated                               1871 non-null   bool
 13  MaterialIncidents                         1871 non-null   bool
 14  OccDateEntered                            1871 non-null   datetime64[ns]
 15  Cyberbullying                             1871 non-null   bool
 16  Harassment_Intimidation_Bullying          1871 non-null   bool
 17  MaterialSexualInNature                    1871 non-null   bool
 18  InvolveStudentOnStudentConduct            1871 non-null   bool
 19  CRA832ConductAViolation                   1871 non-null   bool
 20  Day of Week                               1871 non-null   object
 21  School Day                                1871 non-null   object
 22  Nearest School Day                        1871 non-null   datetime64[ns]
 23  Final Day to ENTER - 1 Day                1871 non-null   datetime64[ns]
 24  2 Days                                    1871 non-null   datetime64[ns]
 25  5 Days                                    1871 non-null   datetime64[ns]
 26  10 Days                                   1871 non-null   datetime64[ns]
dtypes: bool(7), datetime64[ns](10), int64(2), object(8)
memory usage: 319.8+ KB

In [44]:
material_df['Entered on Time'] = np.where(material_df['PrincInformed'] <= material_df['Final Day to ENTER - 1 Day'], 'YES', 'NO')

In [45]:
material_df['Investigated on Time'] = np.where(material_df['CRA832InitialInvestigationCompletionDate'] <= material_df['5 Days'], 'YES', 'NO')

In [46]:
material_df['Investigated on Time'] = np.where(material_df['CRA832InitialInvestigationCompletionDate'].isnull(), ' ', material_df['Investigated on Time'])

In [47]:
material_df['Updated on Time'] = np.where(material_df['Update Date'] <= material_df['10 Days'], 'YES', 'NO')

In [48]:
material_df['Updated on Time'] = np.where(material_df['Update Date'].isnull(), ' ', material_df['Updated on Time'])

In [49]:
#Drop Day of Week, School Day, Nearest School Day, 2 Days, 5 Days

material_df.drop('OccID', axis = 1, inplace = True)
material_df.drop('Harassment_Intimidation_Bullying', axis = 1, inplace = True)
material_df.drop('MaterialSexualInNature', axis = 1, inplace = True)
material_df.drop('Cyberbullying', axis = 1, inplace = True)
material_df.drop('MaterialIncidents', axis = 1, inplace = True)
material_df.drop('BiasRelated', axis = 1, inplace = True)
material_df.drop('Day of Week', axis = 1, inplace = True)
material_df.drop('School Day', axis = 1, inplace = True)
material_df.drop('Nearest School Day', axis = 1, inplace = True)
material_df.drop('2 Days', axis = 1, inplace = True)

In [50]:
material_df.head()

,RowNumber,AcademicYear,DBN,School Name,Classification_Code,Short Description,OORS#,Date,PrincInformed,Update Date,CRA832InitialInvestigationCompletionDate,OccDateEntered,InvolveStudentOnStudentConduct,CRA832ConductAViolation,Final Day to ENTER - 1 Day,5 Days,10 Days,Entered on Time,Investigated on Time,Updated on Time
0,1,2020-2021,07X005,P.S. 5 Port Morris,B35,Posting/Distributing Literature or Material Co...,07X005-071020-0001,2020-07-10,2020-07-10,2020-09-22,2020-07-15,2020-07-13,True,True,2020-07-13,2020-07-17,2020-07-24,YES,YES,NO
1,1,2020-2021,03M291,West End Secondary School,B40,Intimidating and Bullying Behavior (bias),03M291-071720-0003,2020-07-17,2020-07-17,2020-10-06,2020-07-20,2020-07-20,True,True,2020-07-20,2020-07-24,2020-08-03,YES,YES,NO
2,1,2020-2021,02M413,School of the Future High School,B40,Intimidating and Bullying Behavior (bias),02M413-071820-0006,2020-07-18,2020-07-18,2020-09-24,2020-09-24,2020-07-20,True,False,2020-07-20,2020-07-24,2020-08-03,YES,NO,NO
3,1,2020-2021,03M541,Manhattan / Hunter Science High School,B39,Intimidating and Bullying Behavior,03M541-072020-0002,2020-07-20,2020-07-20,2020-07-22,2020-07-22,2020-07-22,True,True,2020-07-21,2020-07-27,2020-08-04,YES,YES,YES
4,1,2020-2021,13K430,Brooklyn Technical High School,B39,Intimidating and Bullying Behavior,13K430-081320-0007,2020-08-13,2020-08-13,2020-09-22,2020-09-21,2020-08-13,True,True,2020-08-14,2020-08-20,2020-08-27,YES,NO,NO

In [51]:
#Export data to excel: https://datatofish.com/export-dataframe-to-excel/
#df.to_excel(r'Path to store the exported excel file\File Name.xlsx', sheet_name='Your sheet name', index = False)
#Formatting: https://xlsxwriter.readthedocs.io/working_with_pandas.html

#material_df.to_excel(r"/Users/holly/Desktop/nycdoe/01142021 Compliance Data FINAL.xlsx", sheet_name='Material',header=True, merge_cells=False, index=False)

In [52]:
#Source: https://xlsxwriter.readthedocs.io/example_pandas_multiple.html

writer = pd.ExcelWriter('/Users/holly/Desktop/nycdoe/01142021 Compliance Data FINAL.xlsx', engine='xlsxwriter')

ideation_df.to_excel(writer, sheet_name='Ideation')
acs_df.to_excel(writer, sheet_name='ACS')
inc_df.to_excel(writer, sheet_name='L1-5')
missing_df.to_excel(writer, sheet_name='Missing')
material_df.to_excel(writer, sheet_name='Material')

writer.save()